<?php 
require_once('./db/connexion.php');
require_once('class_artiste.php');
require_once('class_histoire.php');
require_once('class_ouvrage.php');
require_once('class_film.php');
require_once('class_ville.php');
require_once('class_lier.php');
require_once('class_vivre.php');
require_once('class_contenir.php');
require_once('class_image_ville.php');
require_once('class_comporter.php');
require_once('class_composer.php');
require_once('class_chanter.php');
require_once('class_referencer.php');
require_once('class_upload.php');
require_once('class_video.php');
require_once('class_morceau.php');
require_once('class_son.php');
require_once('class_catblues.php');
require_once('class_blues.php');
require_once('class_analyse.php');
require_once('class_caracteristique.php');
require_once('fonction_formulaire.php');
?>